---
- hosts: localhost
  gather_facts: no
  tasks:

#####################################################################
#################### Deploy from VMware Template ####################
#####################################################################
  - name: Clone the template with static network
    vmware_guest:
      hostname: '{{ vcenter }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: "{{ vm_hostname }}"
      template: "{{ template_name }}"
      datacenter: "TinyTechLabUK"
      folder: /Ansible_Builds
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        boot_firmware: "efi"
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gw }}"
        type: "{{ vm_net_type }}"
        dns_servers:
        - 10.15.0.240
        - 10.15.0.241
        - 10.10.192.240
        connected: yes
        start_connected: yes
      customization:
        autologon: true
        autologoncount: 2
        hostname: "{{ vm_hostname }}"
        runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Scripts\Ansible\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      state: poweredon
      wait_for_ip_address: yes
      wait_for_customization: yes
    delegate_to: localhost
    
#####################################################################
######################## Add to Ansible Host Group###################
##################################################################### 

  - name: Add host to group (static)
    add_host:
     hostname: "{{ vm_ip }}"
     groups:
     - newVMDeployment
    when: vm_net_type == "static"
   
  - name: Add host to group (DHCP)
    add_host:
     hostname: "{{ build_dhcp.instance.ipv4 }}"
     groups:
     - newVMDeployment
    when: vm_net_type == "dhcp"
    
  - name: Sleep for 60 seconds to give VM ample time to become reachable
    wait_for:
      timeout: 60

#####################################################################
#####################################################################

#####################################################################
#################### newVMDeployment Play Configuration #############
#####################################################################

- hosts: newVMDeployment
  vars:
    ansible_port: 5985
    ansible_user: ansible
    ansible_password: Password2021
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_scheme: http
    windows_runner: ttl-ansiblenode.internal.tinytechlab.uk
    gather_facts: yes
  tasks: 

#####################################################################
######################## Setting DNS Servers ########################
#####################################################################

  - name: Setup and activate Windows Server via KMS Server
    win_shell: |
      cscript C:\Windows\System32\slmgr.vbs /skms kms.internal.tinytechlab.uk
      cscript C:\Windows\System32\slmgr.vbs /cpky
      cscript C:\Windows\System32\slmgr.vbs /ipk N69G4-B89J2-4G8F4-WWYCC-J464C
      cscript C:\Windows\System32\slmgr.vbs /ato
    delegate_to: "{{ vm_ip }}"

#####################################################################
#####################################################################

#####################################################################
######################## Domain Check & Join ########################
#####################################################################

- hosts: newVMDeployment
  vars:
    ansible_port: 5985
    ansible_user: ansible
    ansible_password: Password2021
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_scheme: http
    windows_runner: ttl-ansiblenode.internal.tinytechlab.uk
    gather_facts: yes
  tasks:
    
  - name: Test if computer is domain joined
    win_shell: |
      (gwmi win32_computersystem).partofdomain
    register: isDomainJoined
    when: join_domain == "YES"
    
  - name: Set fact for if computer is domain joined
    set_fact:
      domain_joined: "{{ isDomainJoined.stdout | regex_replace('(\\r\\n)','') }}"
    when: join_domain == "YES"
    
  - name: Report that computer is domain joined
    debug:
      msg: "Computer is already joined to the domain."
    when: domain_joined == true and join_domain == "YES"
    
  - name: Report that computer will be joined to the domain.
    debug:
      msg: "Computer is not joined to any domain, joining now.."
    when: domain_joined == false and join_domain == "YES"
    
  - name: Join Domain
    win_shell: |
      netdom join $env:computername /domain:internal.tinytechlab.uk /UserD:{{ lookup("env", "ANSIBLE_NET_USERNAME") }} /PasswordD:{{ lookup("env", "ANSIBLE_NET_PASSWORD") }} /ou:"OU\=Virtual_Servers,OU\=TinyTechLabUK,DC\=internal,DC\=tinytechlab,DC\=uk"
    when: domain_joined == false and join_domain == "YES"
    
  - name: Report that machine will be rebooted
    debug:
      msg: "Rebooting computer now.."
    when: domain_joined == false and join_domain == "YES"
      
  - name: Reboot machine after domain join
    win_reboot:
      reboot_timeout: 3600
    when: domain_joined == false and join_domain == "YES"
    
  - name: Test if computer is domain joined after reboot
    win_shell: |
      (gwmi win32_computersystem).partofdomain
    register: isDomainJoined
    when: domain_joined == false and join_domain == "YES"
    
  - name: Set fact for if computer is domain joined
    set_fact:
      domain_joined: "{{ isDomainJoined.stdout | regex_replace('(\\r\\n)','') }}"
    when: domain_joined == false and join_domain == "YES"
    
  - name: Report that join domain has failed.
    debug:
      msg: "Domain Join has failed. Please check logs."
    when: domain_joined == false and join_domain == "YES"
    delegate_to: "{{ vm_ip }}"

#####################################################################
#####################################################################
