---
- hosts: localhost
  gather_facts: no
  tasks:

#####################################################################
#################### Deploy from VMware Template ####################
#####################################################################
  - name: Clone the template with static network
    vmware_guest:
      hostname: '{{ vcenter }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: "{{ vm_hostname }}"
      template: "{{ template_name }}"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        boot_firmware: "efi"
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gw }}"
        type: "{{ vm_net_type }}"
        dns_servers: "{{ vm_dns }}"
      customization:
        autologon: true
        hostname: "{{ vm_hostname }}"
        dns_servers:
        - "{{ vm_dns }}"
        domain: internal.tinytechlab.uk
        username: "svcacctj@internal.tinytechlab.uk"
        password: "{{ Domain_Join_Account }}"
        runonce:
        - powershell.exe -ExecutionPolicy Unrestricted -File C:\Scripts\Ansible\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      state: poweredon
      wait_for_ip_address: yes
      wait_for_customization: yes
    delegate_to: localhost
    when: vm_net_type == "static"
    
    
  - name: Clone the template with dhcp network
    vmware_guest:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: "{{ vm_hostname }}"
      template: "{{ template_name }}"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        boot_firmware: "efi"
      networks:
      - name: "{{ vm_network }}"
        type: "{{ vm_net_type }}"
        dns_servers: "{{ vm_dns | default(omit) }}"
      customization:
        autologon: true
        hostname: "{{ vm_hostname }}"
        dns_servers:
        - "{{ vm_dns }}"
        domain: uk.wal-mart.com
        username: "svcacctj@internal.tinytechlab.uk"
        password: "{{ Domain_Join_Account }}"
        runonce:
        - powershell.exe -ExecutionPolicy Unrestricted -File C:\Scripts\Ansible\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      state: poweredon
      wait_for_ip_address: yes
      wait_for_customization: yes
    register: result
    delegate_to: localhost
    when: vm_net_type == "dhcp"
    
  - name: Add host to group
    add_host:
      hostname: "{{ vm_ip }}{{ result.instance.ipv4 }}"
      groups:
      - newVMDeployment
      
  - name: Sleep for 60 seconds to give VM ample time to become reachable
    wait_for:
      timeout: 60
