---
- hosts: localhost
  gather_facts: no
  tasks:

#####################################################################
#################### Deploy from VMware Template ####################
#####################################################################
  - name: Clone the template with static network
    vmware_guest:
      hostname: '{{ vcenter }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: "{{ vm_hostname }}"
      template: "{{ template_name }}"
      datacenter: "TinyTechLabUK"
      folder: /Ansible_Builds
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        boot_firmware: "efi"
      networks:
        name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gw }}"
        type: "{{ vm_net_type }}"
        dns_servers: "{{ vm_dns_1 }}"
        dns_servers: "{{ vm_dns_2 }}"
        dns_servers: "{{ vm_dns_3 }}"
#      customization:
#        autologon: true
#        autologoncount: 2
#        hostname: "{{ vm_hostname }}"
#        dns_servers:
#        - "{{ vm_dns_1 }}"
#        - "{{ vm_dns_2 }}"
#        - "{{ vm_dns_3 }}"
#        dns_suffix: "internal.tinytechlab.uk"
#        joindomain: internal.tinytechlab.uk
#        domainadmin: "svcacctj@internal.tinytechlab.uk"
#        domainadminpassword: "{{ Domain_Join_Account_Username }}"
#        password: '{{ WORKGROUP_Administrator }}'
#      wait_for_ip_address: yes
#      wait_for_customization: yes
#        runonce:
#        - powershell.exe -ExecutionPolicy Unrestricted -File C:\Scripts\Ansible\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      state: poweredon
#    delegate_to: localhost
