---
- hosts: all
  gather_facts: yes
  tasks:

#####################################################################
#################### Deploy from VMware Template ####################
#####################################################################
  - name: Clone the template with static network
    vmware_guest:
      hostname: '{{ vcenter }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: "{{ vm_hostname }}"
      template: "{{ template_name }}"
      datacenter: "TinyTechLabUK"
      folder: /Ansible_Builds
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        boot_firmware: "efi"
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gw }}"
        type: "{{ vm_net_type }}"
        dns_servers:
        - 10.15.0.240
        - 10.15.0.241
        connected: yes
        start_connected: yes
      customization:
        autologon: true
        autologoncount: 2
        hostname: "{{ vm_hostname }}"
        runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Scripts\Ansible\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      state: poweredon
      wait_for_ip_address: yes
      wait_for_customization: yes
    delegate_to: localhost
    
#####################################################################
######################## Add to Ansible Host Group###################
##################################################################### 

  - name: Add host to group (static)
    add_host:
     hostname: "{{ vm_ip }}"
     groups:
     - newVMDeployment
    when: vm_net_type == "static"
   
  - name: Add host to group (DHCP)
    add_host:
     hostname: "{{ build_dhcp.instance.ipv4 }}"
     groups:
     - newVMDeployment
    when: vm_net_type == "dhcp"
    
  - name: Sleep for 60 seconds to give VM ample time to become reachable
    wait_for:
      timeout: 60

#####################################################################
#####################################################################

#####################################################################
#################### newVMDeployment Play Configuration #############
#####################################################################

- hosts: newVMDeployment
  vars:
    windows_runner: ttl-ansiblenode.internal.tinytechlab.uk
    gather_facts: yes
  tasks: 

#####################################################################
######################## Setting DNS Servers ########################
#####################################################################

  - name: Setup and activate Windows Server via KMS Server
    win_shell: |
      cscript C:\Windows\System32\slmgr.vbs /skms kms.internal.tinytechlab.uk
      cscript C:\Windows\System32\slmgr.vbs /cpky
      cscript C:\Windows\System32\slmgr.vbs /ipk N69G4-B89J2-4G8F4-WWYCC-J464C
      cscript C:\Windows\System32\slmgr.vbs /ato
    delegate_to: "{{ vm_ip }}"
