---
- hosts: localhost
  gather_facts: no
  tasks:

#####################################################################
#################### Deploy from VMware Template ####################
#####################################################################
  - name: Clone the template with static network
    command: hostname
    vmware_guest:
      hostname: '{{ vcenter }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: "{{ vm_hostname }}"
      template: "{{ template_name }}"
      datacenter: "TinyTechLabUK"
      folder: /Ansible_Builds
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        boot_firmware: "efi"
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gw }}"
        type: "{{ vm_net_type }}"
        dns_servers:
        - 10.15.0.240
        - 10.15.0.241
        connected: yes
        start_connected: yes
      customization:
        autologon: true
        autologoncount: 2
        hostname: "{{ vm_hostname }}"
        runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Scripts\Ansible\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      state: poweredon
      wait_for_ip_address: yes
      wait_for_customization: yes
    delegate_to: localhost

#####################################################################
######################## Setting DNS Servers ########################
######################################################################
  - name: Setting up Variables for Windows Node
    vars:
    	ansible_user: 'jdadmin@internal.tinytechlab.uk'
    	ansible_password: 'D0n4!d50n2020D0n4!d50n2020'
    	ansible_port: 5985
    	ansible_winrm_transport: credssp
    	ansible_connection: winrm
    	ansible_winrm_server_cert_validation: ignore
    	ansible_winrm_scheme: http
    	windows_runner: ttl-ansiblenode.internal.tinytechlab.uk

---
- hosts: localhost
  tasks:
  - name: Setup and activate Windows KMS
    command: "{{ windows_runner }}
    win_shell
      cscript C:\Windows\System32\slmgr.vbs /skms kms.internal.tinytechlab.uk
      cscript C:\Windows\System32\slmgr.vbs /cpky
      cscript C:\Windows\System32\slmgr.vbs /ipk N69G4-B89J2-4G8F4-WWYCC-J464C
      cscript C:\Windows\System32\slmgr.vbss /ato
