---
- hosts: localhost
  gather_facts: no
  tasks:

#####################################################################
#################### Deploy from VMware Template ####################
#####################################################################
  - name: Clone the template with static network
    vmware_guest:
      hostname: '{{ vcenter }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      name: "{{ vm_hostname }}"
      template: "{{ template_name }}"
      datacenter: "TinyTechLabUK"
      folder: /Ansible_Builds
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ vm_datastore }}"
      hardware:
#        type: "thin"
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
        boot_firmware: "efi"
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gw }}"
        type: "{{ vm_net_type }}"
#        dns_servers: "{{ vm_dns_1 }}"
#        dns_servers: "{{ vm_dns_2 }}"
#        dns_servers: "{{ vm_dns_3 }}"
        connected: yes
        start_connected: yes
      customization:
        autologon: true
        autologoncount: 2
        hostname: "{{ vm_hostname }}"
#        dns_servers:
#        - "{{ vm_dns_1 }}"
#        - "{{ vm_dns_2 }}"
#        - "{{ vm_dns_3 }}"
#        joindomain: 'internal.tinytechlab.uk'
#        domainadmin: 'svcacctj@internal.tinytechlab.uk'
#        domainadminpassword: 'wgqGG3ALqnjDaQ7tVcbu'
#       password: '{{ "WORKGROUP_Administrator") }}'
        runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Scripts\Ansible\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      state: poweredon

#####################################################################
######################## Domain Check & Join ########################
#####################################################################
# host should be a member of domain ansible.vagrant; module will ensure the hostname is mydomainclient
# and will use the passed credentials to join domain if necessary.
# Ansible connection should use local credentials if possible.
# If a reboot is required, the second task will trigger one and wait until the host is available.
- hosts: winclient
  gather_facts: no
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: 'internal.tinytechlab.uk'
      hostname: "{{ vm_hostname }}"
      domain_admin_user: svcacctj@internal.tinytechlab.uk
      domain_admin_password: wgqGG3ALqnjDaQ7tVcbu
      domain_ou_path: "OU\=Virtual_Servers,OU\=TinyTechLabUK,DC\=internal,DC\=tinytechlab,DC\=uk"
      state: domain
    register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required

#####################################################################
#####################################################################
